[package]
name = "c_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
# low-level-ir = { git = "https://github.com/Zycrasion/low-level-ir", version = "0.11.2" }
low-level-ir = { path = "../low-level-ir" }